
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - dana.794.dana.794
  resources:
  - subspaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dana.794.dana.794
  resources:
  - subspaces/status
  verbs:
  - get
  - patch
  - update
